# Generated by Django 3.1 on 2020-09-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0004_auto_20200927_2128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='picture',
            new_name='profile_pic',
        ),
    ]
